{{- range $name, $svc := .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
    {{- include "instacommerce.labels" $ | nindent 4 }}
spec:
  replicas: {{ $svc.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: {{ $name }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ $name }}
                topologyKey: topology.kubernetes.io/zone
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ $name }}
                topologyKey: kubernetes.io/hostname
      containers:
        - name: {{ $name }}
          image: "{{ $.Values.global.image.registry }}/{{ $svc.image }}:{{ $svc.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.global.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: {{ $svc.port }}
              name: http
          resources:
            {{- toYaml $svc.resources | nindent 12 }}
          env:
            {{- range $k, $v := $svc.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: {{ $svc.readinessPath | default "/actuator/health/readiness" }}
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: {{ $svc.livenessPath | default "/actuator/health/liveness" }}
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
          startupProbe:
            httpGet:
              path: {{ $svc.livenessPath | default "/actuator/health/liveness" }}
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 20
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
---
{{- end }}
