{{- range $name, $svc := .Values.services }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
    {{- include "instacommerce.labels" $ | nindent 4 }}
---
{{- end }}
