ALTER TYPE payment_status ADD VALUE IF NOT EXISTS 'AUTHORIZE_PENDING' BEFORE 'AUTHORIZED';
ALTER TYPE payment_status ADD VALUE IF NOT EXISTS 'CAPTURE_PENDING' AFTER 'AUTHORIZED';
ALTER TYPE payment_status ADD VALUE IF NOT EXISTS 'VOID_PENDING' AFTER 'CAPTURE_PENDING';
